### ISSUE TITLE
Build error in sample

### ISSUE THREAD

**Issue by YaiEf** [yuvaltz/Granular#2]
Any ideas about this?

Error	5	The "CompileXaml" task failed unexpectedly.
System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Users\x\Downloads\GranularApplication1\packages\Saltarelle.Granular.0.1.3\build\Granular.BuildTasks.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\Users\x\Downloads\GranularApplication1\packages\Saltarelle.Granular.0.1.3\build\Granular.BuildTasks.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.

   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName)
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName)
   at Granular.BuildTasks.CompileXaml.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext()

	C:\Users\x\Downloads\GranularApplication1\packages\Saltarelle.Granular.0.1.3\build\Granular.targets	24	5	GranularApplication1.Web

**Comment by MihaMarkic** [comment]
Perhaps blocking web content is applied. Check right click on Granular.BuildTasks.dll and see if there is Unblock option.

**Comment by yuvaltz** [comment]
I couldn't reproduce this exception, but it seems that VS refuses to load the build task dll.
Try moving the Solution folder out of the Downloads folder, see if it helps.
If not, try to recompile Granular.BuildTasks locally and replace the dll in the package folder.

**Comment by Cyral** [comment]
I have the same issue, the unblock checkbox didn't work for me, but compiling Granular and using the compiled dlls instead of those from the package (just overwriting them) made it possible to run the WPF version at least (Web complains about it not being .NET 2.0)

**Comment by diab0l** [comment]
Had the same issue and unblocking Granular.BuildTasks.dll resolved it.

**Comment by Suchiman** [comment]
The easiest solution to this is to unblock the zip archive before extracting it (or using 7-zip for example which doesn't sets the dangerous file flag), then this error doesn't happen.

**Comment by Flem100** [comment]
Right click the .zip file, goto properties and choose unblock. After that extract the files. That solved the problem for me
